<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <NoWarn>CS1591;IDE0005;CS0618</NoWarn>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.1" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../JingleBox2.csproj" />
    <ProjectReference Include="../../Rack.SoundDevices/JingleBox2.Rack.SoundDevices.csproj" />
  </ItemGroup>
</Project>
